apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  type: ClusterIP
  selector:
    app: argocd-example-app
  ports:
    - name: http
      port: 80
      targetPort: 80
